### ISSUE TITLE
Error p.408. eq (9.49)

### ISSUE THREAD

**Issue by esabo** [goropikari/SolutionForQuantumComputationAndQuantumInformation#2]
The sum $\sum_i (p_i - q_i) = \sum_i p_i - \sum_i q_i = 1 - 1 = 0$? So the error needs to be fixed a different way?

**Comment by goropikari** [comment]
I see. I agree with you.
I think I was wrong in my calculation from first to second line.
Since $(p_i - q_i) \leq |p_i - q_i|$ and $0 \leq \Tr (P \sigma_i) \leq 1$, then we obtain
$\sum_i (p_i - q_i) \Tr(P \sigma_i) \leq \sum_i |p_i - q_i| \Tr(P \sigma_i) \leq \sum_i |p_i - q_i| = 2D(p_i, q_i)$.

Thank you for your comments!
